email_reading_task:
  
  expected_output: >
    A summary of the email content highlighting the main topic, product details, and any notable points.


slogan_generation_task:
  description: >
    Use the summary provided by Mail_Reader to generate a catchy and engaging slogan 
    that encapsulates the essence of the email content. 
    Ensure the slogan is suitable for marketing purposes and resonates with the target audience.
  expected_output: >
    A single, impactful slogan that effectively communicates the key message of the email summary.


image_description_task:
  description: >
    Based on the slogan provided by Slogan_Maker and the email summary from Mail_Reader, 
    generate a detailed description for an image that visually represents the content. 
    The description should include elements that align with the slogan and the main points of the email.
  expected_output: >
    A comprehensive image description that includes all necessary visual elements 
    to be used by Image_Generator for creating the final image.


image_generation_task:
  description: >
    Create a high-quality image based on the detailed description provided by Image_Creator. 
    The image should visually capture the essence of the slogan and the email content, 
    ensuring it is suitable for marketing use.
  expected_output: >
    A visually appealing image that accurately reflects the provided description 
    and aligns with the marketing message.


social_media_posting_task:
  description: >
    Using the slogan from Slogan_Maker and the image generated by Image_Generator, 
    create an optimized post for LinkedIn.
  expected_output: >
    One social media post for LinkedIn that includes the slogan, image, relevant hashtags, and necessary links.